### ISSUE TITLE
nxegl: Error is 30 'Read-only file system'.

### ISSUE THREAD

**Issue by copart** [losuler/com.cisco.PacketTracer#16]
I tried to install by running

```
flatpak-builder --install --user build com.cisco.PacketTracer.yml
```

It ran for a log time, and ended with the following lines:

```
Installing app/com.cisco.PacketTracer/x86_64/master
nxegl: Error opening log file.
nxegl: Error is 30 'Read-only file system'.
nxeglInterposeInit: Output suppressed.
nxegl: Error opening log file.
nxegl: Error is 30 'Read-only file system'.
nxeglInterposeInit: Output suppressed.
nxegl: Error opening log file.
nxegl: Error is 30 'Read-only file system'.
nxeglInterposeInit: Output suppressed.
nxegl: Error opening log file.
nxegl: Error is 30 'Read-only file system'.
nxeglInterposeInit: Output suppressed.
nxegl: Error opening log file.
nxegl: Error is 30 'Read-only file system'.
nxeglInterposeInit: Output suppressed.
nxegl: Error opening log file.
nxegl: Error is 30 'Read-only file system'.
nxeglInterposeInit: Output suppressed.
Pruning cache
```

It did install, since I can do this:

```
/usr/bin/flatpak run com.cisco.PacketTracer
```

However, this returns an error:

```
nxegl: Error opening log file.
nxegl: Error is 30 'Read-only file system'.
nxeglInterposeInit: Output suppressed.
error: Failed to sync with dbus proxy
```

Was I supposed to install as root (ie sudo)?

Note: I am a noob with flatpak.

**Comment by losuler** [comment]
I'm not sure what could have caused this, I haven't seen this error before. You shouldn't need to install it with root/sudo, I never do so at least. My guess is this might be filesystem or distro related (I use Fedora).

I'd first just try uninstalling (`flatpak remove com.cisco.PacketTracer`) and installing again (`flatpak-builder --install --user build com.cisco.PacketTracer.yml`). This should be fine as your configuration is stored in `~/.var/app/com.cisco.PacketTracer` and isn't deleted when you remove the Flatpak (if this matters to you).

**Comment by copart** [comment]
Hmm, same issue... I also use Fedora, however, I use KDE instead of Gnome.

**Comment by losuler** [comment]
Might be worth trying again with the latest changes (move to KDE platform libs). If you're still having the same issue, let me know.
