### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by pchmykh** [losuler/com.cisco.PacketTracer#20]
Actual filename I believe is Packet_Tracer821_amd64_signed.deb, doesn't work for now. I have changed the name in included files, but got this error:
```
Composing metadata...
Run failed, some data was ignored.
Errors were raised during this compose run:
com.cisco.PacketTracer
  E: icon-not-found

general
  E: filters-but-no-output
Refer to the generated issue report data for details on the individual problems.
Error: ERROR: appstreamcli compose failed: Child process exited with code 1
```

**Comment by losuler** [comment]
Sorry about getting to this late. I've resolved both issues now. The icon missing (https://github.com/losuler/com.cisco.PacketTracer/commit/4046cce634a58700c691243dbcd9cfe5d0d14062) and the filename changing (https://github.com/losuler/com.cisco.PacketTracer/commit/73f2242e590286b61a0d4e9940034fbc64685e38) after being rehosted on skillsforall.
