### ISSUE TITLE
Console Fonts are not monospace

### ISSUE THREAD

**Issue by IceWreck** [losuler/com.cisco.PacketTracer#4]
![image](https://user-images.githubusercontent.com/18102790/144891213-00b16b08-b2e5-4782-9a29-13c5e4cf2924.png)

It doesn't seem to recognize system fonts and I only get two options for changing the CLI font and both of them don't work.

**Comment by losuler** [comment]
I believe the console font not being monospace is a bug in the 8.0.1 release, because I was able to reproduce it and it appears it's been fixed in the 8.1.0 release (which I have just now pushed the changes for).

**Comment by IceWreck** [comment]
Thanks, Just updated my install. Everything works fine now.
